### PR TITLE
Update MeSH import for 2023+ data

### PR DESCRIPTION
**Pull request by hrshdhgd**
There is no key named `["concepts"]` in any dictionary within `descriptor_record` which is a `List[dict]` rather than a `dict` as the code seems to expect.

P.S: @cthoyt

### CODE REVIEW

**Comment by hrshdhgd** [comment]
How do I check that? All I ran is 
```
import pyobo
df = pyobo.get_sssom_df(resource)
df.to_csv(output_file, sep="\t", index=False)
```

It takes a long time to run. It is currently stuck at: 
```
INFO: [2023-07-26 14:54:44] pystow.utils - downloading with urllib from http://snomed.info/sct/900000000000207008/version/20200131 to ../.data/pyobo/raw/snomedct/2020-01-31/20200131
```

Do I need credentials for `snomedct`? I did get credentials for `icd10`.

**Comment by cthoyt** [comment]
There a setting for this function to turn off name lookup and make it faster

**Comment by hrshdhgd** [comment]
> There a setting for this function to turn off name lookup and make it faster

There doesn't seem to be an `if` condition or a flag for processing `get_name()` if that is what I should be looking for:


https://github.com/pyobo/pyobo/blob/3013564266efa4c82db95791f2f0b4b6a3e41630/src/pyobo/api/xrefs.py#L104-L155

**Comment by hrshdhgd** [comment]
@cthoyt : I managed to get the command to run entirely. I managed to do so after adding a filter to the DataFrame in `get_sssom_df()` 
```
df = df[~df["target_ns"].isin(["icd10","snomedct"])]
```
The reason I did so was because in the `for` loop, when a row in `df` had `target_ns` equal to either of these 2, the program appeared to halt. I could be totally wrong and it could be taking a long time to get the data but it seemed too long and the % bar seemed to be frozen at 0%. I [created a login for ICD10](https://icd.who.int/icdapi) to get access to their resources via an API token.

Question:
1. Do I need to do the same for SNOMED-CT?
2. Would waiting longer (>2 hours) complete this process?

**Comment by cthoyt** [comment]
When I’m back next week I can update this function to have a flag to not look up labels

**Comment by cthoyt** [comment]
@hrshdhgd thanks for pointing this out. I was finally able to look into the data itself and it appears that the MeSH 2023 data has changed its structure. I updated your code to remain backwards compatible with 2022 and earlier data.

**Pull request merged**
